fix(findlibraries): prevent TypeError object[key].match is not a function (fixes #320) (#321)
* refactor: make .getUbernameFromH5pJson public

* test(saveh5p): test all real-world examples from content-type-hub

* test(saveh5p): enable LibraryManager to load libraries from examples

* fix(findlibraries): check if library-field is a string (fixes #320)

* test(saveh5p): copy content to tmp-dir to not influence other tests

* test(unit): extract hub-content before running unit-tests

* test(coverage): extract hub-content for coverage report

* test(saveh5p): move to integration-tests and fix errors

* refactor(h5peditor): removed redundant ubername parsing